### ISSUE TITLE
Default value of an object pattern property should not change type if it's assignable

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#189]
https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_type_checker/tests/conformance/types/nonPrimitive/nonPrimitiveAndEmptyObject.ts#L6-L17

This should success.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/29931815/199987891-d4c50f08-601a-4ace-9ac5-c6b8f81a19a7.png">

`access_property` of `((BarProps#1 & object) | {})` is expected to fail, because `{}` does not have the property.
But the type of `fooProps` should be `(BarProps#1 & object)` (without union)

I think the logic at https://github.com/dudykr/stc/blob/d121f20feb4f7a66e96a1b093dfadc507baf8610/crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs#L483-L500 is problematic, and I think we should adjust it to ignore default value if the type of the default value is assignable to the original type.

**Comment by kharvd** [comment]
Hi @kdy1, I'd like to give it a try!

**Comment by kdy1** [comment]
Thanks!

**Comment by kharvd** [comment]
Is the `object` part relevant here? Looks like tsc [infers](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgIUygAUoIwBnOAbwCg4G4AjI08gfgC44KYpkA5gG5aAX1q1QkWIhRosuOADEIENpRr1G6VeopcCrMpRHjaAE2DYANkTzYISXnB0RuKtcYoiHT+NRddLzgAXhpROAiw1xFaVz0AOhYSYxEgA) `BarProps` even when `fooProps` has type `BarProps`, without the `object` intersection.

I would guess we should infer `BarProps | DefaultValue` if `DefaultValue` is not assignable to `BarProps & object`, and just `BarProps` otherwise. `{}` is assignable to `BarProps & object` (or `BarProps` fwiw), so we should infer `BarProps & object`

**Comment by kdy1** [comment]
I think you are right, nice catch! Thank you.

I tried [incompatible default value](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgIUygAUoIwBnOAbwCg4G4AjI08gfgC44KYpkA5gG5aAX1q1QkWIhRosuOADEIENpRr1G6VeopcCrMpRHjaAE2DYANkTzYISXnB0RuKtcYoiHT+NRddLzgAXhpMEIBGUTgYsNcRWlc9ADoWEmMRIA) and it matches with your observation
