### ISSUE TITLE
Use `NoSuchProperty` for `globalThis.name`

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#337]
https://github.com/dudykr/stc/blob/41b76af273b27a172b6f8e50d7ea36f1bf0eda46/crates/stc_ts_type_checker/tests/conformance/es6/arrowFunction/emitArrowFunctionThisCapturingES6.ts#L2-L8

Should fail with `globalThis has no property named 'name'` but currently it fails with an assignment failure.

```
thread 'conformance::es6::arrowFunction::emitArrowFunctionThisCapturingES6.ts' panicked at '
============================================================
TS2322

  x context:
  | lhs = void;
  | rhs = string;
  | context: `fail!()` called from assign/mod.rs:1640
  | LHS (final): void;
  | RHS (final): string;
  | AssignFailed {
  |     span: Span {
  |         lo: BytePos(
  |             87,
  |         ),
  |         hi: BytePos(
  |             100,
  |         ),
  |         ctxt: #0,
  |     },
  |     cause: [],
  | }
   ,-[$DIR/tests/conformance/es6/arrowFunction/emitArrowFunctionThisCapturingES6.ts:7:5]
 7 | this.name = x
   : ^^^^^^^^^^^^^
   `----

    ============================================================
1 unmatched errors out of 1 errors. Got 1 extra errors.
Wanted: [RefError { line: 7, column: 10, code: "TS2339" }]
Unwanted: [(7, "TS2322")]', crates/stc_ts_type_checker/tests/tsc.rs:748:17
```

**Comment by iheyunfei** [comment]
I've been digging for a while, I found the problem is that
https://github.com/dudykr/stc/blob/9c3d3a3fbc69966e779a85dd3dfdf5c765efa9ec/crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs#L1233
when you call `get_global_var` with `sym: 'name'`, you will get actually get a result rather than __not existed__.

https://github.com/dudykr/stc/blob/9c3d3a3fbc69966e779a85dd3dfdf5c765efa9ec/crates/stc_ts_env/src/lib.rs#L103

Here, `builtin.vars` indeed contains a key which is `name`.

And the `builtin` is generated here

https://github.com/dudykr/stc/blob/9c3d3a3fbc69966e779a85dd3dfdf5c765efa9ec/crates/stc_ts_file_analyzer/src/env.rs#L286

with libs
```
[
    Es5,
    Es2015Core,
    Es2015Collection,
    Es2015Symbol,
    Es2015Iterable,
    Es2015Generator,
    Es2015Promise,
    Es2015Proxy,
    Es2015Reflect,
    Es2015SymbolWellknown,
    Es2015,
    Es2016ArrayInclude,
    Es2016,
    Es2017Object,
    Es2017Sharedmemory,
    Es2017String,
    Es2017Intl,
    Es2017Typedarrays,
    Es2017,
    Es2018Asynciterable,
    Es2018Asyncgenerator,
    Es2018Promise,
    Es2018Regexp,
    Es2018Intl,
    Es2018,
    Es2019Array,
    Es2019Object,
    Es2019String,
    Es2019Symbol,
    Es2019,
    Es2020Bigint,
    Es2020Promise,
    Es2020Sharedmemory,
    Es2020String,
    Es2020SymbolWellknown,
    Es2020Intl,
    Es2020,
    Dom,
    WebworkerImportscripts,
    Scripthost,
    DomIterable,
    Es2015Full,
    Es2016Full,
    Es2017Full,
    Es2018Full,
    Es2019Full,
    Es2020Full,
]
```
which actually declares a `name` variable in global.

**Comment by kdy1** [comment]
Yes, `globalThis.name` is a special value.
We should pinpoint it from `access_property_inner`
