### ISSUE TITLE
`&&=` should create type fact for the RHS

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#595]
https://github.com/dudykr/stc/blob/273356f921c6152b5a45c41527923a86361ebe13/crates/stc_ts_type_checker/tests/conformance/es2021/logicalAssignment/logicalAssignment4.ts#L28-L33

In the code above, `thing &&= thing.original` should pass, but stc fails to validate it

**Comment by hwoongkang** [comment]
## Question

How can I know whether two different `stc_ts_types::Type` are referencing the "same token" (I am a newbie in compiler codes, sorry for any incorrect terms)

## Idea

I think the crack is in here,
[`stc/crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs:769`](https://github.com/dudykr/stc/blob/273356f921c6152b5a45c41527923a86361ebe13/crates/stc_ts_file_analyzer/src/analyzer/control_flow.rs#L769-L773),
which is like below:

```
                        op!("&&=") => {
                            lhs_ty = self.apply_type_facts_to_type(TypeFacts::Falsy, lhs_ty);


                            Type::new_union(span, vec![lhs_ty, rhs_ty.clone()])
                        }
```

## What I want to do

If we can somehow identify that `lhs_ty` and `rhs_ty` is referencing the "same token",

since the [logical and operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment) assigns --or evaluates the rhs-- only if the lhs is truthy,

We can apply `TypeFacts::Truthy` to rhs.
